language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update
 - sudo apt-get install -y python-opencv python-tk
 - sudo dpkg -L python-opencv

install:
  - "pip install --pre -r requirements.txt"

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
  - cd unittests
  - python main.py